### ISSUE TITLE
When training with llama3.1, loss suddenly became larger during the pretrain stage

### ISSUE THREAD

**Issue by aoji0606** [aimagelab/LLaVA-MORE#3]
![image](https://github.com/user-attachments/assets/0072f9b6-4cc5-4b37-973c-28e822fde39f)

**Comment by federico1-creator** [comment]
Hi @aoji0606,
I saw that you closed the issue. Did you solve the problem?

**Comment by aoji0606** [comment]
Yeah, that's my problem
