### ISSUE TITLE
zero2 deepspeed json is not uploaded

### ISSUE THREAD

**Issue by sahilqure** [aimagelab/LLaVA-MORE#8]
zero2 deepspeed json is not uploaded, please upload it

**Comment by linxi1158** [comment]
you find it where in [LLava](https://github.com/haotian-liu/LLaVA/blob/main/scripts/zero2.json)

**Comment by federico1-creator** [comment]
Hi @sahilqure, thank you for your interest in our project!

Now you can find the deepspeed configuration (`zero2.json` and `zero3.json`) in [the following folder](https://github.com/aimagelab/LLaVA-MORE/tree/main/scripts)
