### ISSUE TITLE
LoRA Finetuning

### ISSUE THREAD

**Issue by tsunghan-wu** [aimagelab/LLaVA-MORE#9]
Hi,

Thanks for the great work! Have you tried fine-tuning the model with LoRA as I found it degrades the performance a bit?
If so, can you share the alpha and r parameters (or any experiences)? Thanks!

**Comment by federico1-creator** [comment]
Hi @tsunghan-wu, thank you!

We haven't run many experiments using the LoRA configuration, so I'm unable to recommend optimal hyperparameters. 
Maybe you might want to follow the suggested alpha and r values from the LLaVA repo.
`    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 `

**Comment by tsunghan-wu** [comment]
Thanks for sharing!
